### ISSUE TITLE
Web form for prover

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#10]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

----------------------------------------

Create a web page to communicate data with a Haskell back-end. Suggestion: include one field labelled "goal", send it to backend, reverse the string and send it back for display.

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/10

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
