### ISSUE TITLE
Command line option to override constant "tool" in Build

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#11]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

----------------------------------------

Add the command line option:

-build Stack
-build Cabal

to override the default value of "tool". Look into packages "lambda-options" (which I do not know) or "System.Console.GetOpt" in base (which I know and use in Continuous.hs).

Think of using unsafePerformIO (from System.IO.Unsafe) in the definition of "tool" to gain access to command line arguments.

With this design, any executable linked with Build will be able to make use of that command line option.

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/11

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
