### ISSUE TITLE
Swap out MissingH

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#12]
Originally reported by: **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**

----------------------------------------

MissingH is not being developed anymore and the author(s) doesn't seem to be responding or taking any action on the reported issues.

It has been a probable cause of build problems with stack in the past (for me personally) and lately with the introduction of `isSymbolicLink` in `directory-1.2.6.0` there's an ambiguity between the version from 'directory' and the one from 'unix'.

Right now, we use a couple of string utility functions from `Data.String.Utils`, and `map`, `replace`, and `split` functions `from Data.List.Utils`, from MissingH.

The following list of alternatives is incomplete, so we'd either bring code over directly from MissingH find other existing packages that have the utilities we use.

Alternatives:

* `split`: We can use `Data.List.Split.splitOn` from the split package instead of `Data.List.Utils.split` and/or `Data.String.Utils.split` from MissingH. As of now, the mentioned methods of MissingH and split have the same behaviour for non-empty lists, and the split package seems to handle the empty list case more sanely than MissingH.

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/12

**Comment by aminb** [comment]
*Original comment by* **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**:

----------------------------------------

MissingH is working out fine now

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
