### ISSUE TITLE
Fix up the errors in Logic.Expr.TypeChecking

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#15]
Originally reported by: **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**

----------------------------------------

Currently, `Logic.Expr.TypeChecking` is not in the build system. However, since it'll probably be relevant for future work, it's good to resolve its issues and make it compile.

Uncomment `-- Logic.Expr.TypeChecking` in `logic/literate-unitb-logic.cabal`.

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/15

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
