### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#16]
Originally reported by: **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**

----------------------------------------

Fix build on Linux.

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/16

**Comment by aminb** [comment]
*Original comment by* **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**:

----------------------------------------

Pull request #14

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
