### ISSUE TITLE
Implement syntax for record lookup

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#24]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/24

**Comment by aminb** [comment]
*Original comment by* **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**:

----------------------------------------

Done

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
