### ISSUE TITLE
Add \Int as a valid expression

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#25]
Originally reported by: **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**

----------------------------------------

... and make sure that it does not resolve in instantiating more assumptions than needed in the conversion to first order logic

Def's should probably not be considered when instantiating assumptions.

Or maybe only the Def's that are referenced in named assumptions and goal

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/25

**Comment by aminb** [comment]
*Original comment by* **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**:

----------------------------------------

In b6d351ac

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
