### ISSUE TITLE
Add type annotation to record expressions

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#28]
Originally reported by: **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**

----------------------------------------

Add type annotation (t) to RecordExpr

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/28

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
