### ISSUE TITLE
including interval_theory results in ValUnknown

### ISSUE THREAD

**Issue by aminb** [literate-unitb/literate-unitb#29]
Originally reported by: **Amin Bandali (Bitbucket: [aminb](https://bitbucket.org/aminb), GitHub: [aminb](https://github.com/aminb))**

----------------------------------------

Including interval_theory always results in ValUnknown for validities.

----------------------------------------
- Bitbucket: https://bitbucket.org/literateunitb/literate-unitb/issue/29

**Comment by aminb** [comment]
*Original comment by* **Simon Hudon (Bitbucket: [cipher2048](https://bitbucket.org/cipher2048), GitHub: Unknown)**:

----------------------------------------

In 3dc45e9

**Comment by bandali** [comment]
Kamino closed and cloned this issue to unitb/literate-unitb-complete
